version: "3"

services:
  postgres:
    container_name: postgres
    image: "postgres:17.4-alpine3.21"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=QWERasdfzxcv1234POIklasjdhflktrewtNG
      - PGDATA=/data/pgdata/
      - POSTGRES_USER=audio_service
    volumes:
      - .containers/postgres/:/data/pgdata/
 
  minio:
    container_name: minio
    command: server --console-address ":9001" /data
    image: "minio/minio"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_PASSWORD=QWERASDFZXCVasdfqwerzxcv1234
      - MINIO_ROOT_USER=audio_service
  
  mongo:
    image: "mongo:8.0.6-noble"
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=audio_service
      - MONGO_INITDB_ROOT_PASSWORD=QWERASDFZXCVasdfqwerzxcv1234
    ports:
      - "27017:27017"
